/**
 * @module systemd
 *
 * This module provides operations for managing systemd services, units, and various systemd daemon
 * configurations.
 */

export {
  SYSTEMD_SYSTEM_PATH,
  SYSTEMD_USER_PATH,
  type SystemdScope,
  type SystemdScopeOptions,
  getSystemdConfigDropInPath,
  getSystemdConfigPath,
  getUnitPath,
  parseKeyValue,
} from './systemd/common.js';
export { type CoredumpConf } from './systemd/coredump.js';
export {
  type JournalRead,
  type JournalVacuumOptions,
  journalRead,
  journalVacuum,
} from './systemd/journal.js';
export { type JournaldConf } from './systemd/journald.js';
export {
  LOGIND_CONF_PATH,
  type LogindConf,
  type LogindHandleAction,
  type LogindIdleAction,
} from './systemd/logind.js';
export { daemonReload } from './systemd/manager.js';
export {
  RESOLVED_CONF_PATH,
  type ResolvedConf,
  type ResolvedLinkConf,
} from './systemd/resolved.js';
export {
  type GetServiceInfoOptions,
  type ServiceInfo,
  type ServiceOptions,
  getServiceInfo,
  enableService,
  disableService,
  startService,
  stopService,
  restartService,
  reloadService,
} from './systemd/service.js';
export { SLEEP_CONF_PATH, type SleepConf } from './systemd/sleep.js';
export {
  SYSTEM_CONF_PATH,
  USER_CONF_PATH,
  type SystemManagerConf,
  type SystemManagerCPUPressureWatch,
  type SystemManagerCrashAction,
  type SystemManagerCtrlAltDelBurstAction,
  type SystemManagerIOPressureWatch,
  type SystemManagerLogTarget,
  type SystemManagerMemoryPressureWatch,
  type SystemManagerNUMAPolicy,
  type SystemManagerProtectSystem,
  type SystemManagerRestrictFileSystemAccess,
  type SystemManagerShowStatus,
  type SystemManagerStandardOutput,
  type SystemManagerStatusUnitFormat,
} from './systemd/system-conf.js';
export {
  type SetHostnameOptions,
  type SetLocaleOptions,
  type SetTimezoneOptions,
  setHostname,
  setLocale,
  setTimezone,
} from './systemd/system.js';
export {
  type SysusersConf,
  type SysusersEntry,
  type SysusersType,
  parseSysusersConf,
  serializeSysusersConf,
} from './systemd/sysusers.js';
export { TIMESYNCD_CONF_PATH, type TimesyncdConf } from './systemd/timesyncd.js';
export {
  type TmpFilesConf,
  type TmpFilesEntry,
  type TmpfilesType,
  parseTmpFilesConf,
  serializeTmpFilesConf,
} from './systemd/tmpfiles.js';
export {
  ZRAM_GENERATOR_CONF_PATH,
  ZRAM_GENERATOR_DROP_IN_PATH,
  type ZramGeneratorConf,
  type ZramGeneratorDeviceConf,
} from './systemd/zram-generator.js';
export type {
  AutomountSectionOptions,
  AutomountUnitConf,
  AutomountUnitDropIn,
  BindIPv6Only,
  DeviceUnitConf,
  DeviceUnitDropIn,
  InstallSectionOptions,
  MountSectionOptions,
  MountUnitConf,
  MountUnitDropIn,
  OomPolicy,
  PathSectionOptions,
  PathUnitConf,
  PathUnitDropIn,
  ScopeSectionOptions,
  ScopeUnitConf,
  ScopeUnitDropIn,
  ServiceExitType,
  ServiceNotifyAccess,
  ServiceRestart,
  ServiceRestartMode,
  ServiceSectionOptions,
  ServiceType,
  ServiceUnitConf,
  ServiceUnitDropIn,
  SliceSectionOptions,
  SliceUnitConf,
  SliceUnitDropIn,
  SocketProtocol,
  SocketSectionOptions,
  SocketTimestamping,
  SocketUnitConf,
  SocketUnitDropIn,
  SwapSectionOptions,
  SwapUnitConf,
  SwapUnitDropIn,
  TargetUnitConf,
  TargetUnitDropIn,
  TimeoutFailureMode,
  TimerSectionOptions,
  TimerUnitConf,
  TimerUnitDropIn,
  UnitSectionOptions,
  UnitType,
} from './systemd/unit.js';
export type {
  NetworkConf,
  NetworkAddress,
  NetworkBridgeFDB,
  NetworkBridgeMDB,
  NetworkBridgePort,
  NetworkCAN,
  NetworkDHCPPrefixDelegation,
  NetworkDHCPServer,
  NetworkDHCPServerStaticLease,
  NetworkDHCPv4,
  NetworkDHCPv6,
  NetworkIPoIB,
  NetworkIPv6AcceptRA,
  NetworkIPv6AddressLabel,
  NetworkIPv6PREF64Prefix,
  NetworkIPv6Prefix,
  NetworkIPv6RoutePrefix,
  NetworkIPv6SendRA,
  NetworkLink,
  NetworkLLDP,
  NetworkMatch,
  NetworkNeighbor,
  NetworkNetwork,
  NetworkNextHop,
  NetworkQDisc,
  NetworkRoute,
  NetworkRoutingPolicyRule,
  NetworkSRIOV,
} from './systemd/networkd/network.js';
export type {
  NetDevConf,
  NetDevBAREUDP,
  NetDevBatmanAdvanced,
  NetDevBond,
  NetDevBridge,
  NetDevFooOverUDP,
  NetDevGENEVE,
  NetDevHSR,
  NetDevIPOIB,
  NetDevIPVLAN,
  NetDevIPVTAP,
  NetDevL2TP,
  NetDevL2TPSession,
  NetDevMACVLAN,
  NetDevMACVTAP,
  NetDevMACsec,
  NetDevMACsecReceiveAssociation,
  NetDevMACsecReceiveChannel,
  NetDevMACsecTransmitAssociation,
  NetDevMatch,
  NetDevNetDev,
  NetDevPeer,
  NetDevTap,
  NetDevTun,
  NetDevTunnel,
  NetDevVLAN,
  NetDevVRF,
  NetDevVXCAN,
  NetDevVXLAN,
  NetDevWLAN,
  NetDevWireGuard,
  NetDevWireGuardPeer,
  NetDevXfrm,
} from './systemd/networkd/netdev.js';
export type {
  LinkConf,
  LinkEnergyEfficientEthernet,
  LinkLink,
  LinkMatch,
  LinkSRIOV,
} from './systemd/networkd/link.js';
