name: Deploy Docs to GitHub Pages
on:
  push:
    paths:
      - docs/**
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

env:
  ACTION_CACHE_PATH: |
    ~/.bun/install/cache
    node_modules/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v6
        with:
          path: ${{ env.ACTION_CACHE_PATH }}
          key: ${{ runner.os }}
      - uses: withastro/action@v6
        with:
          path: ./docs/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v5
        id: deployment
